server:
#  port: 8080
  port: 443
  ssl:
    key-store: classpath:www.tianyaguet.club.jks
    key-store-password: 5k7b37kiw68tis
    key-store-type: JKS
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coal_management?useSSL=false
    username: root
    password: '053073@Zd'